export const MAX_HINTS = 3;
export const DISCOVERIES_PER_HINT = 3;
export const REGEN_MS = 10 * 60_000;

/**
 * Limited hints: up to MAX_HINTS charges. One comes back every REGEN_MS (also while the game is
 * closed), and every DISCOVERIES_PER_HINT new recipes earn one. Pure: callers pass `now`.
 */
export class HintBank {
  constructor({ charges = MAX_HINTS, progress = 0, regenAt = null } = {}) {
    this.charges = Math.min(MAX_HINTS, Math.max(0, charges));
    this.progress = progress;
    this.regenAt = this.charges < MAX_HINTS ? regenAt : null;
  }

  static fromSave(saved, now) {
    const bank = new HintBank(saved ?? {});
    if (bank.charges < MAX_HINTS && bank.regenAt === null) bank.regenAt = now + REGEN_MS;
    bank.tick(now);
    return bank;
  }

  /** Adds any charges that regenerated by `now`. Returns how many were added. */
  tick(now) {
    if (this.regenAt === null) return 0;
    let added = 0;
    while (this.charges < MAX_HINTS && now >= this.regenAt) {
      this.charges++;
      added++;
      this.regenAt += REGEN_MS;
    }
    if (this.charges >= MAX_HINTS) this.regenAt = null;
    return added;
  }

  /** Uses one hint. Returns false when there are none left. */
  spend(now) {
    this.tick(now);
    if (this.charges <= 0) return false;
    this.charges--;
    if (this.regenAt === null) this.regenAt = now + REGEN_MS;
    return true;
  }

  /**
   * Call once per newly discovered recipe. Returns true when it earned a hint.
   * While full, progress is kept (not wasted), so the first discovery after spending pays out.
   */
  onDiscovery(now) {
    this.progress = Math.min(this.progress + 1, DISCOVERIES_PER_HINT);
    if (this.progress < DISCOVERIES_PER_HINT || this.charges >= MAX_HINTS) return false;
    this.progress = 0;
    this.charges++;
    if (this.charges >= MAX_HINTS) this.regenAt = null;
    else if (this.regenAt === null) this.regenAt = now + REGEN_MS;
    return true;
  }

  /** Discoveries still needed for the next earned hint. */
  get discoveriesToNext() {
    return Math.max(1, DISCOVERIES_PER_HINT - this.progress);
  }

  msUntilNext(now) {
    return this.regenAt === null ? 0 : Math.max(0, this.regenAt - now);
  }

  toSave() {
    return { charges: this.charges, progress: this.progress, regenAt: this.regenAt };
  }
}
